apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: test-lab
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    root_url = http://localhost:3000
    
    [security]
    admin_user = admin
    admin_password = admin
    
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/kubernetes-dashboard.json
    
    [alerting]
    enabled = true
    
    [log]
    mode = console
    level = info
    
    [metrics]
    enabled = true
    
  kubernetes-dashboard.json: |
    {
      "annotations": {"list": []},
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {"type": "row", "title": "Summary", "gridPos": {"h": 1, "w": 24, "x": 0, "y": 0}},
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "API RPS (total)",
          "fieldConfig": {"defaults": {"unit": "reqps"}},
          "targets": [{"expr": "sum(rate(api_requests_total[1m]))", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 0, "y": 1}
        },
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "API RPS (success)",
          "fieldConfig": {"defaults": {"unit": "reqps"}},
          "targets": [{"expr": "sum(rate(api_requests_success_total[1m]))", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 6, "y": 1}
        },
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "API RPS (errors)",
          "fieldConfig": {"defaults": {"unit": "reqps"}},
          "targets": [{"expr": "sum(rate(api_requests_failed_total[1m]))", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 12, "y": 1}
        },
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "Active Requests",
          "fieldConfig": {"defaults": {"unit": "none"}},
          "targets": [{"expr": "sum(api_active_requests)", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 18, "y": 1}
        },
        {"type": "row", "title": "API Latency & Throughput", "gridPos": {"h": 1, "w": 24, "x": 0, "y": 5}},
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "API Requests Rate (by status)",
          "fieldConfig": {"defaults": {"unit": "reqps"}},
          "targets": [
            {"expr": "sum by (status)(rate(api_requests_total[1m]))", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 6}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "API p95 Latency (s)",
          "fieldConfig": {"defaults": {"unit": "s"}},
          "targets": [
            {"expr": "histogram_quantile(0.95, sum(rate(api_request_duration_seconds_bucket[5m])) by (le))", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 6}
        },
        {"type": "row", "title": "Resources", "gridPos": {"h": 1, "w": 24, "x": 0, "y": 12}},
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "CPU Usage (namespace total, cores)",
          "fieldConfig": {"defaults": {"unit": "cores"}},
          "targets": [
            {"expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"test-lab\",container!=\"POD\"}[2m]))", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 13}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "Memory Usage (namespace total)",
          "fieldConfig": {"defaults": {"unit": "bytes"}},
          "targets": [
            {"expr": "sum(container_memory_usage_bytes{namespace=\"test-lab\",container!=\"POD\"})", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 13}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "API CPU by Pod (cores)",
          "fieldConfig": {"defaults": {"unit": "cores"}},
          "targets": [
            {"expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace=\"test-lab\",pod=~\"api-.*\",container!=\"POD\"}[2m]))", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 19}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "API Memory by Pod",
          "fieldConfig": {"defaults": {"unit": "bytes"}},
          "targets": [
            {"expr": "sum by (pod)(container_memory_usage_bytes{namespace=\"test-lab\",pod=~\"api-.*\",container!=\"POD\"})", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 19}
        },
        {"type": "row", "title": "Kubernetes State", "gridPos": {"h": 1, "w": 24, "x": 0, "y": 25}},
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "Running Pods (namespace)",
          "targets": [{"expr": "sum(kube_pod_status_phase{namespace=\"test-lab\",phase=\"Running\"})", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 0, "y": 26}
        },
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "Total Restarts (namespace)",
          "targets": [{"expr": "sum(kube_pod_container_status_restarts_total{namespace=\"test-lab\"})", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 6, "y": 26}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "Recent Restarts (by pod, 5m)",
          "targets": [{"expr": "sum by (pod)(increase(kube_pod_container_status_restarts_total{namespace=\"test-lab\"}[5m]))", "refId": "A"}],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 26}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "HPA Desired vs Available Replicas (API)",
          "targets": [
            {"expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"test-lab\",horizontalpodautoscaler=\"api-hpa\"}", "refId": "A"},
            {"expr": "kube_deployment_status_replicas_available{namespace=\"test-lab\",deployment=\"api\"}", "refId": "B"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 30}
        },
        {"type": "row", "title": "Database", "gridPos": {"h": 1, "w": 24, "x": 0, "y": 36}},
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "DB Size (bytes)",
          "fieldConfig": {"defaults": {"unit": "bytes"}},
          "targets": [{"expr": "db_size_bytes", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 0, "y": 37}
        },
        {
          "datasource": "Prometheus",
          "type": "stat",
          "title": "DB Rows (approx)",
          "targets": [{"expr": "db_rows", "refId": "A"}],
          "gridPos": {"h": 4, "w": 6, "x": 6, "y": 37}
        },
        {
          "datasource": "Prometheus",
          "type": "barchart",
          "title": "DB Ops Rate by Operation",
          "targets": [{"expr": "sum by (operation)(rate(db_operations_total[1m]))", "refId": "A"}],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 37}
        },
        {"type": "row", "title": "Errors by Endpoint", "gridPos": {"h": 1, "w": 24, "x": 0, "y": 43}},
        {
          "datasource": "Prometheus",
          "type": "barchart",
          "title": "Error Rate (by endpoint)",
          "targets": [{"expr": "sum by (endpoint)(rate(api_requests_total{status=~\"4..|5..\"}[5m]))", "refId": "A"}],
          "gridPos": {"h": 6, "w": 24, "x": 0, "y": 44}
        }
      ],
      "refresh": "5s",
      "schemaVersion": 27,
      "style": "dark",
      "tags": ["kubernetes", "api", "monitoring"],
      "templating": {"list": []},
      "time": {"from": "now-30m", "to": "now"},
      "timepicker": {},
      "timezone": "",
      "title": "Kubernetes Test Lab Dashboard",
      "uid": "k8s-test-lab",
      "version": 2
    }