apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: test-lab
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    root_url = http://localhost:3000
    
    [security]
    admin_user = admin
    admin_password = admin
    
    [auth.anonymous]
    enabled = true
    org_role = Viewer
    
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/kubernetes-dashboard.json
    
    [alerting]
    enabled = true
    
    [log]
    mode = console
    level = info
    
    [metrics]
    enabled = true
    
  kubernetes-dashboard.json: |
    {
      "annotations": {"list": []},
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "Total CPU Usage (Cores)",
          "fieldConfig": {"defaults": {"unit": "cores"}},
          "targets": [
            {"expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"test-lab\"}[5m]))", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 0}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "Total Memory Usage (GB)",
          "fieldConfig": {"defaults": {"unit": "bytes", "decimals": 2}},
          "targets": [
            {"expr": "sum(container_memory_usage_bytes{namespace=\"test-lab\"})", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 0}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "Total API Requests (Rate)",
          "fieldConfig": {"defaults": {"unit": "reqps"}},
          "targets": [
            {"expr": "sum(rate(api_requests_total[1m]))", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 6}
        },
        {
          "datasource": "Prometheus",
          "type": "timeseries",
          "title": "Live Pods Count (Timeline)",
          "fieldConfig": {"defaults": {"unit": "none"}},
          "targets": [
            {"expr": "sum(kube_pod_status_phase{namespace=\"test-lab\",phase=\"Running\"})", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 6}
        },
        {
          "datasource": "Prometheus",
          "type": "barchart",
          "title": "System CPU Usage by Service (Cores)",
          "fieldConfig": {"defaults": {"unit": "cores"}},
          "targets": [
            {"expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"test-lab\"}[5m])) by (container)", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 12}
        },
        {
          "datasource": "Prometheus",
          "type": "barchart",
          "title": "System Memory Usage by Service (MB)",
          "fieldConfig": {"defaults": {"unit": "bytes", "decimals": 2}},
          "targets": [
            {"expr": "sum(container_memory_usage_bytes{namespace=\"test-lab\"}) by (container)", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 12}
        },
        {
          "datasource": "Prometheus",
          "type": "table",
          "title": "Crashed Pods (Restarts)",
          "fieldConfig": {"defaults": {"unit": "none"}},
          "targets": [
            {"expr": "sum(kube_pod_container_status_restarts_total{namespace=\"test-lab\"}) by (pod, container)", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 0, "y": 18}
        },
        {
          "datasource": "Prometheus",
          "type": "table",
          "title": "Failed Pods",
          "fieldConfig": {"defaults": {"unit": "none"}},
          "targets": [
            {"expr": "count(kube_pod_status_phase{namespace=\"test-lab\",phase=\"Failed\"}) by (pod)", "refId": "A"}
          ],
          "gridPos": {"h": 6, "w": 12, "x": 12, "y": 18}
        }
      ],
      "refresh": "5s",
      "schemaVersion": 27,
      "style": "dark",
      "tags": ["kubernetes", "api", "monitoring"],
      "templating": {"list": []},
      "time": {"from": "now-30m", "to": "now"},
      "timepicker": {},
      "timezone": "",
      "title": "Kubernetes Test Lab Dashboard",
      "uid": "k8s-test-lab",
      "version": 1
    }