apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: test-lab
  labels:
    app: postgres
data:
  POSTGRES_DB: testdb
  POSTGRES_USER: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
  
  # PostgreSQL tuning for testing
  postgresql.conf: |
    # Connection settings
    max_connections = 200
    
    # Memory settings
    shared_buffers = 256MB
    effective_cache_size = 1GB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    
    # WAL settings
    wal_level = minimal
    max_wal_senders = 0
    
    # Query tuning
    random_page_cost = 1.1
    
    # Logging
    log_statement = 'none'
    log_duration = off
    
    # Performance
    synchronous_commit = off
    full_page_writes = off
    
  init.sql: |
    -- Initial database setup
    CREATE SCHEMA IF NOT EXISTS public;
    
    -- Create indexes for better performance
    CREATE INDEX IF NOT EXISTS idx_tasks_completed ON tasks(completed);
    CREATE INDEX IF NOT EXISTS idx_tasks_created_at ON tasks(created_at);
    CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks(priority);
    
    -- Grant permissions
    GRANT ALL PRIVILEGES ON DATABASE testdb TO postgres;
    GRANT ALL PRIVILEGES ON SCHEMA public TO postgres;