apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: test-lab
  labels:
    app: api
    component: backend
  annotations:
    service.beta.kubernetes.io/external-traffic: "Local"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: api
  sessionAffinity: None