apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: test-lab
  labels:
    app: prometheus
    component: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: prometheus